[build]
  publish = "client/build"
  command = "npm install --prefix functions && npm install --prefix client && npm run build --prefix client"

[functions]
  directory = "functions"

[[redirects]]
  from = "/builder/*"
  to = "/.netlify/functions/builderProxy?path=:splat"
  status = 200
  force = true
